export { HomePage } from './HomePage'
export { IndustriesPage } from './IndustriesPage'
export { CaseStudiesPage } from './CaseStudiesPage'
export { AboutContactPage } from './AboutContactPage'
export { AuthPage } from './AuthPage'
export { TermsPage, PrivacyPage } from './LegalPages'
export { OnboardingPage } from './app/OnboardingPage'
export { DashboardPage } from './app/DashboardPage'
